version: '3.6'

services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    links:
      - db
    ports:
      - 8080:8080
